name: Build and Deploy to Cloud Run
on:
  push:
    branches:
      - main
    paths:
     - 'document.txt'
     - 'new folder/**'
     - '.github/workflows/blank.yml'
        
jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
           contents: 'read'
           id-token: 'write'

    steps:
      - uses: actions/checkout@v3
        with:
         fetch-depth: 0

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
                credentials_json: ${{ secrets.RUN_SA_KEY}}
                service_account: ${{ secrets.SA_EMAIL }}

      - name: Set up Cloud SDK 1
        uses: google-github-actions/setup-gcloud@v1
        
      - name: Connect VM
        run: |
          #gcloud compute instances describe instance-2 --zone=us-west4-b
          gcloud compute ssh instance-2 --zone=us-west4-b

      - name: Upload file to GCS
        run: |
          #gsutil cp desu.txt gs://desu-project/uploadfiles/
          #gsutil cp * gs://desu-project/uploadfiles/
          #gsutil -m cp -r * gs://desu-project/uploadfiles/
          
          # Copy file VM 
          #gcloud compute scp document.txt instance-2:/home/gangeria6060/project --project=panel-379806 --zone=us-west4-b
          #gcloud compute scp --recurse document.txt root@instance-2:/home/gangeria6060/project --project=panel-379806 --zone=us-west4-b
          gcloud compute scp document.txt instance-2:/home/gangeria6060/project --zone=us-west4-b
          
       
          
